### PR TITLE
rollback TBD change

### PR DESCRIPTION
**Pull request by wenyikuang**

### CODE REVIEW

**Comment by brgix** [comment]
Hi @wenyikuang : I co-wrote TBD with @macumber. We weren't aware there was issue with TBD. The latest release is now [v3.3.0](https://github.com/rd2/tbd/releases/tag/v3.3.0), which we would greatly like to see updated in openstudio-gems (not regressed back to v3.2.2). Could you provide us with a description of your issue(s), with TBD versions > 3.2.2? Thanks.

**Comment by wenyikuang** [comment]
Hi @brgix , @kbenne and I are trying to debugging issue in https://github.com/NREL/OpenStudio/issues/5027 and faced the issue:


```
➜  build git:(osExtension071) ✗ ./Products/openstudio  classic  execute_ruby_script ~/Desktop/loadgems.rb

┌────────────────────────────────────────────────────────────────────────────────┐

│  The `classic` command is deprecated and will be removed in a future release   │

└────────────────────────────────────────────────────────────────────────────────┘

Error executing argv: ["execute_ruby_script", "/home/kbenne/Desktop/loadgems.rb"]

Error: Unable to resolve dependency: 'tbd (~> 3.2.3)' requires 'osut (~> 0.3.0)' in :/ruby/2.7.0/rubygems/resolver.rb:235:in search_for'
```

We are doing experiment to see whether that's the place broken.

**Comment by brgix** [comment]
Hmm. Thanks @wenyikuang. Have you and @kbenne tried [v3.3.0](https://rubygems.org/gems/tbd/versions/3.3.0)? I don't remember why, but TBD [v3.2.3](https://rubygems.org/gems/tbd/versions/3.2.3) explicitly required OSut **v0.3.0** (which seems to be the issue). The latest release just pulls the latest OSut gem available, just like [v3.2.2](https://rubygems.org/gems/tbd/versions/3.2.2) did originally. Fingers crossed.

**Comment by kbenne** [comment]
Thanks for the tip to try v3.3.0 @brgix.

**Pull request closed without merging**
