### PR TITLE
#4969 - add json_schemer 2.0.0

### PR DESCRIPTION
**Pull request by jmarrec**
add json_schemer 2.0.0 for:

* https://github.com/NREL/OpenStudio/issues/4969

* Companion PR: https://github.com/NREL/OpenStudio/pull/4974

@wenyikuang

### CODE REVIEW

**Comment by jmarrec** [comment]
@wenyikuang, If you want to merge this one, the mac M1 one is hosted on my google drive. I'll put the link on slack.

**Comment by wenyikuang** [comment]
Got the Mac arm64 build from Julien. Will update this PR and the one in SDK together once I found the place to upload.

**Comment by jmarrec** [comment]
@wenyikuang S3:openstudio-resources/dependencies/

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/pull/4974 was merged, tested everything is fine.

@wenyikuang I don't have write access to this repo and need one approving reviewer. Seems you also don't. Pinging @tijcolem to approve.

**Review by shorowit — APPROVED** [review]

**Review by wenyikuang — COMMENTED** [review]
Since we are conusuming it in OS [here](https://github.com/NREL/OpenStudio/commit/b0f0f906a805cb42b45e242c1046d09d8a68ffd7). Just merge it.

**Pull request merged**
