### PR TITLE
bump version of openstudio-workflow

### PR DESCRIPTION
**Pull request by nllong**
@tijcolem -- Rubygems.org is taking a while to recognize the release, but it is there: https://rubygems.org/gems/openstudio-workflow

### CODE REVIEW

**Comment by jmarrec** [comment]
I did a couple of changes to this PR and to extension gem (https://github.com/NREL/openstudio-extension-gem/pull/82) to try and get it to build. So I can then get https://github.com/NREL/OpenStudio/pull/4093

On a side note I noticed that Jenkins wasn't picking up the conan dependencies from the NREL remote but from conan-center, and as a result the dbm extension wasn't configured properly during the build of ruby on unix, so I pushed a commit on cbci_jenkins to make sure NREL's remote is first in line for conan @tijcolem

**Comment by jmarrec** [comment]
Windows is failing because of openstudio-standards very long paths. Git cloning the repo fails as a whole basically.

https://ci.commercialbuildings.dev/blue/organizations/jenkins/openstudio-gems-windows/detail/PR-31/3/pipeline/26

**Comment by nllong** [comment]
I just released openstudio version 0.3.0 and updated this Gemfile (@jmarrec )

**Comment by jmarrec** [comment]
Thanks  @nllong !

**Comment by tijcolem** [comment]
I'll move the build tree up to root c:\  for Windows to make room for some extra chars.  @mdahlhausen FYI on the long path issue

**Comment by mdahlhausen** [comment]
ughh.  We shortened some files in openstudio-standards last release to avoid this issue.  Seems like I'll need to do it again for the necb regression tests.

**Comment by mdahlhausen** [comment]
@tijcolem @asparke2 perhaps one solution is to omit the test directory from the version of the gem that gets built into OpenStudio. Is that possible?

**Comment by tijcolem** [comment]
I think that is what is happening on release builds. That is omitted and everything builds fine, but during test cycles such as this that dir gets sucked into the build and causes issues.  @jmarrec had some ideas on how to handle this. Perhaps he can chime in here with his thoughts.

**Comment by jmarrec** [comment]
The test folder has two issues we face when consuming the git:
* It has very long paths
* It weights a whooping 512MB (as of yesterday)

There aren't great ways to handle that, but I see three:

* There is a way to do a sparse git checkout (https://git-scm.com/docs/git-sparse-checkout), where you first tell git which files/folders to actually checkout, and I suppose we could make a simple & easy rake task on openstudio-standards that would produce the commands needed to do a partial checkout excluding the test folder. But I'm not sure how you can integrate that into bundle gemspec consuming process.
* One option would be to make the `test/` portion of openstudio-standards a git submodule. That means you host it in another repo, and add it as a submodule to openstudio-standards. It'd be more annoying for you to work with it, though you can develop the test/ submodule from your local checkout of openstudio-standards.  For consuming the gem it's easy though, easy: `gem 'rugged', git: 'git://github.com/libgit2/rugged.git', submodules: false` (submodules default to false anyways)
* Release RCs on rubygems, so we can avoid pulling from git altogether.

**Pull request merged**
