### PR TITLE
Bundler bump to 2.1.x

### PR DESCRIPTION
**Pull request by tijcolem**
Replaces https://github.com/NREL/openstudio-gems/pull/10

### CODE REVIEW

**Comment by jmarrec** [comment]
CI can't build the gem because this needs to happen first: https://github.com/NREL/openstudio-extension-gem/pull/34

```
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 2.1.0)

    openstudio-gems was resolved to 3.0.0, which depends on
      openstudio-extension (= 0.1.2) was resolved to 0.1.2, which depends on
        bundler (~> 1.9)

  Current Bundler version:
    bundler (2.1.0)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
./openstudio-gems/ruby/2.5.0/bin/bundle _2.1.0_ lock --add_platform ruby

```

**Comment by jmarrec** [comment]
Bringing back the comments from #10:

Fix #8 ?

Perhaps should be changed to ~> 2.0 instead (meaning any 2.x is fine)
Potentially could fix the issue NREL/OpenStudio#3733

Fix also needs to happen on Jenkins, NREL/cbci_jenkins_libs#62

**Comment by tijcolem** [comment]
Yes, I pinged @nllong who is going to update these for bundler update. 
Should we lock bundler to 2.1.x series so in the off chance something doesn't break when it jumps say from say 2.1.0 to 2.2.0?

**Comment by jmarrec** [comment]
I honestly don't have enough experience with bundler and gem development to know whether they break stuff in minor releases. @nllong or @asparke2 are probably good candidates as they have long standing experience with bundler

**Comment by asparke2** [comment]
@jmarrec I personally haven't ever had any issues updating bundler; I suspect they are extra careful not to break stuff because it is the package manager.

**Comment by jmarrec** [comment]
Thanks @asparke2.

So we probably relax the _pessimistic version constraint_ and do `spec.add_development_dependency 'bundler', '~> 2.1'` meaning `  (meaning ` '>= 2.1'    and '< 3.0'`). ` instead of this PR's `spec.add_development_dependency 'bundler', '~> 2.1.0'` (meaning ` '>= 2.1'.0    and '< 2.2'`)

https://guides.rubygems.org/patterns/#pessimistic-version-constraint

**Pull request merged**
