### PR TITLE
Upgrade dependencies + Native gems: sqlite3-ruby, nokogiri, jaro_winkler 

### PR DESCRIPTION
**Pull request by jmarrec**
#18 + https://github.com/sparklemotion/sqlite3-ruby/pull/285

https://github.com/sparklemotion/sqlite3-ruby#label-Compilation+and+Installation
> Install SQLite3, enabling the option SQLITE_ENABLE_COLUMN_METADATA (see www.sqlite.org/compile.html for details).

conan sqlite3 already has that enabled by default:

https://github.com/conan-io/conan-center-index/blob/f06abbdccdc839f473fc8c3c59ad76d1c9f0d282/recipes/sqlite3/all/conanfile.py#L33

So good to go

### CODE REVIEW

**Comment by jmarrec** [comment]
at 0b019ba, linux doesn't have sqlite3-dev installed, mac reports this:

```
Using sqlite3 1.3.13.20180326210955 from https://github.com/jmarrec/sqlite3-ruby.git (at MSVC_support@69bbc8f)
Build static extension: ext/sqlite3/extconf.rb
NameError: undefined local variable or method `dest_path' for
#<StaticExtensionPlugin:0x00007fab4dd210e0>
An error occurred while installing sqlite3 (1.3.13.20180326210955), and Bundler
cannot continue.
```

**Comment by tijcolem** [comment]
I see the same error on windows regarding `NameError: undefined local variable or method 'dest_path' for`

The 'dest_path' var is set in lib/rubygems_plugin.rb which is what creates the statically compiled ruby gems during the `rake make_package` task.

**Comment by tijcolem** [comment]
Looks like a simple fix. Just need to change this to `tmp_dest` 
https://github.com/NREL/openstudio-gems/blob/develop/lib/rubygems_plugin.rb#L99

**Comment by tijcolem** [comment]
Okay, added that fix in for dest_path var and also added in nokogiri to this branch, 

This should now have #18 + sparklemotion/sqlite3-ruby#285 + #19  with updated Jenkins file to run conan related deps during install.

**Comment by jmarrec** [comment]
For Nokogiri, ref:
https://github.com/sparklemotion/nokogiri/issues/2015
https://github.com/sparklemotion/nokogiri/pull/2016

**Comment by jmarrec** [comment]
@tijcolem I have reverted https://github.com/NREL/openstudio-gems/pull/20/commits/125bb6115d7409a73e39aa5d5822bf57f3ef22a3 since it broke the pipeline. We can address that later.

**Pull request merged**
